# managed by ivn-term

[settings]
experimental = true
python.default_packages_file = "~/.config/mise/default-python-packages"

[tools]
bun = "latest"
go = "latest"
node = "22"
"npm:@mariozechner/pi-coding-agent" = "latest"
python = "latest"
rust = "latest"
zig = "latest"
